### ISSUE TITLE
Extension Manager keeps telling "Update: New version is available" even after updating

### ISSUE THREAD

**Issue by stormlogix** [xdreamer/searchtablejs#17]
Dokuwiki's Extension Manager updates the files but keeps telling "Update: New version 2018-10-12 is available."

**Comment by cvoltz** [comment]
The `plugin.info.txt` needs to be updated. Run this command from the root of your dokuwiki installation directory and the problem will go away:
```
sed --in-place 's/2015-03-18/2018-10-12/' lib/plugins/searchtablejs/plugin.info.txt
```

**Comment by xdreamer** [comment]
Fixed with merge from LMS235 (thanks)
