### ISSUE TITLE
Issue with plugin edittable

### ISSUE THREAD

**Issue by giordi** [xdreamer/searchtablejs#2]
Hi, thanks for this plugin :-)!

The compatibility issue with the plugin "edittable" can be by resolved by adding the following function to syntax.php:

function getAllowedTypes() {return array('container','formatting','substition');}

I din't study the parser modes in detail. I just compared the code with the plugin "sortablejs". They had the same compatibility issues with "edittable" and fixed it in version 2.5.

**Comment by LMS235** [comment]
can be marked as "closed" (pull requests are implemented)

**Comment by xdreamer** [comment]
Thanks for support.
