### ISSUE TITLE
new update won't install?

### ISSUE THREAD

**Issue by asheenlevrai** [xdreamer/searchtablejs#21]
Hello :)

I was happy to notice there is a new update.

However, it seems like it won't install or it keeps on offering the update after it was installed
![searchtablejs](https://github.com/xdreamer/searchtablejs/assets/5127613/b45686a3-5caf-48c8-95de-f7c07556fa0c)

Best,
-a-

**Comment by GulaschZange** [comment]
> should be fixed by #22

Hi,

Can you tell me when the update will be published

**Comment by asheenlevrai** [comment]
> should be fixed by #22

It seems like the problem remains unfortunately
![STJS](https://github.com/xdreamer/searchtablejs/assets/5127613/3867a4d7-a65d-4f93-ba00-89e3bce55f10)

Maybe there is something I'm doing wrong?

**Comment by LMS235** [comment]
my request is not merged
you can manually edit the file in your installation

**Comment by xdreamer** [comment]
I'm sorry, I have currently no active installation, so I need to spin up one for testing. If I have some minutes time I will do so and also try on the other issues. I merged all open pull requests so far (untested), hope this helps.

**Comment by LMS235** [comment]
you can close this - after your merge, its OK :)
